### ISSUE TITLE
Other auth mechanisms?

### ISSUE THREAD

**Issue by LarsFronius** [LRDesign/Convection#1]
Hi,
I really like Convection and find it very useful. The groups and user management seems to be very well implemented.
Precisely because it is that well implemented, I'd love to see it working together with an LDAP or Kerberos-Auth-Mechanism.

**Comment by nyarly** [comment]
One thing we're actively interested in is extending the underlying authorization mechanism to use other authentication methods.  We're particularly interested in Devise (and Warden) which _might_ mean LDAP & Kerberos - I'm not sure of the capabilities of Warden.  Please take a look at LogicalAuthz - its the framework behind the authorization for Convection.  There's a single file (by design) that fascades authentication, so even if Warden doesn't suit your needs it should be simple to extend to do what you need.  If you want guidance on that score let us know - we'd be thrilled to give you a hand.
